//src\app\layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Load custom fonts with better loading behavior
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: "swap", // Ensure the font displays immediately with fallback
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  display: "swap", // Ensure the font displays immediately with fallback
});

// Metadata for the page including SEO and social sharing tags
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Open Graph Meta Tags for better social sharing
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://your-app-url.com", // Update with your app URL
    images: [ // Corrected from 'image' to 'images'
      {
        url: "https://your-app-url.com/og-image.png", // Update with your image URL
        width: 800,
        height: 600,
        alt: "Open Graph Image", // Provide an alt text for accessibility
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload font files for improved performance */}
        <link
          rel="preload"
          href="/fonts/GeistVF.woff"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous" // Corrected from 'crossorigin' to 'crossOrigin'
        />
        <link
          rel="preload"
          href="/fonts/GeistMonoVF.woff"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous" // Corrected from 'crossorigin' to 'crossOrigin'
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
